GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type:application/json

{
    
    "name": "pepepe",
    "number": ""
}

###
GET http://localhost:3001/api/persons/5 

###
DELETE http://localhost:3001/api/persons/1