GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
content-Type:application/json

{
    "name": "pelekkkk",
    "number": 12345 
}

###
GET http://localhost:3001/api/persons/2

###
DELETE http://localhost:3001/api/persons/50